### ISSUE TITLE
Cross SDK multisig support

### ISSUE THREAD

**Issue by scholtz** [FrankSzendzielarz/dotnet-algorand-sdk#14]
It would be great if there were some examples on how to use multisig.

I am not sure if this implementation is ok nor if it is cross sdk compatible (with js-algo-sdk) : https://github.com/scholtz/Algorand2FAMultisig/blob/master/Algorand2FAMultisig/MsigExtension/MsigExtension.cs

Use case: 2FA Auth. Multisig with 3 accounts, where one is owned by user and stored in cold storage, second is owned by user and stored in hot wallet, and third account owned by trusted service where which approves the tx if 2FA auth (Google auth) is processed successfully. Threshold for multisig is 2, so that service cannot do any txs, and if service go off user can rekey with the cold storage account.

**Comment by FrankSzendzielarz** [comment]
I am not sure what you mean by "cross SDK compatible". An SDK example with multisigs can be produced yes. There will be a revised SDK examples csproj in the coming week or so.

**Comment by scholtz** [comment]
@FrankSzendzielarz  .. can you reference here the example how to append signature to the multisig please?

"cross SDK compatible" is just the expectation where the serialized data strutcture from js-algo-sdk will be usable in c# sdk .. i assume it  should be easy as this sdk has to output the same stream to the algod server .. 

why did you closed this enhancement when it is not yet resolved?
