### ISSUE TITLE
Abi app call

### ISSUE THREAD

**Issue by scholtz** [FrankSzendzielarz/dotnet-algorand-sdk#18]
Hi @FrankSzendzielarz ,

do you know some best practices how to make abi app call from C# to algoand app?

For example if I want to use Algorand DB storage and create a dotnet repository for https://github.com/algorand-devrel/TEALScript/pull/78/files#diff-ba9d5c4c5f6cc069764a69b782b0ad2b4736fa4b6cfcd621491deda8cd5e8958 , what should i do?

The best would be to have some C# client connector generator as it is in the algokit for pyteal and tealscript ```algokit generate client --language typescript --output AlgorandDBStorageClient.ts artifacts/AlgorandDBStorage.json```

**Comment by FrankSzendzielarz** [comment]
No the SDK has no client generator unfortunately. If you would like to PR it feel free but it would be quite a lot of work an AFAICT the arc4 abi spec is to be superseded (?)

**Comment by scholtz** [comment]
Any update on this? From algorand forum the information regarding arc4 supression has been declined..

**Comment by FrankSzendzielarz** [comment]
Who said anything about suppression? "Superseded" means there was going to be a new version , related to shared arguments in group transactions.  Joe Polny says that since they've shelved or cancelled that effort, IIUC. As for ARC4 client generator feel free to submit upur PR.

**Comment by FrankSzendzielarz** [comment]
Closed
