### ISSUE TITLE
Phantom Placeholder in master branch

### ISSUE THREAD

**Issue by WesleyMiller1998** [FrankSzendzielarz/dotnet-algorand-sdk#4]
There is this phantom project definition in the master branch
```
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Placeholder", "Placeholder\Placeholder.csproj", "{D301FA6F-9FE0-48B0-A08F-EDF4133C6752}"
EndProject
```

I can merge dev-1 with master and PR this removal if you'd like

**Comment by FrankSzendzielarz** [comment]
Thanks @WesleyMiller1998  that should be fixed, along with a bug I found in contract compilation . Seems that there are actually legacy bugs in actual contract compilation, with missing tests in the test folder, so as I go through the compiler tests now I might be updating this repo more often.
