### ISSUE TITLE
Could not deserialize the response body stream as Algorand.V2.Algod.Model.Account.

### ISSUE THREAD

**Issue by JoshOtter** [FrankSzendzielarz/dotnet-algorand-sdk#5]
My team and I are all encountering an error this morning that wasn't there yesterday when we call the DefaultApi.AccountsAsync() method. I had been using the other SDK package under Riley Ge still, but I tried uninstalling it and installing the new Algorand2 package, but ran into the same issue.

Here's the message I'm getting: 

JsonSerializationException: Required property 'creator' not found in JSON. Path 'assets[0]', line 1, position 266.
...
Rethrow as ApiException: Could not deserialize the response body stream as Algorand.V2.Algod.Model.Account.

We're just trying to get a list of assets from the wallet account. Here's the entire error message I'm getting in Unity: 

JsonSerializationException: Required property 'creator' not found in JSON. Path 'assets[0]', line 1, position 266.
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EndProcessProperty (System.Object newObject, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonObjectContract contract, System.Int32 initialDepth, Newtonsoft.Json.Serialization.JsonProperty property, Newtonsoft.Json.Serialization.JsonSerializerInternalReader+PropertyPresence presence, System.Boolean setDefaultValue) (at <f74995119334484fb6db6825be2eac0d>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject (System.Object newObject, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.String id) (at <f74995119334484fb6db6825be2eac0d>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <f74995119334484fb6db6825be2eac0d>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <f74995119334484fb6db6825be2eac0d>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList (System.Collections.IList list, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonArrayContract contract, Newtonsoft.Json.Serialization.JsonProperty containerProperty, System.String id) (at <f74995119334484fb6db6825be2eac0d>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.Object existingValue, System.String id) (at <f74995119334484fb6db6825be2eac0d>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <f74995119334484fb6db6825be2eac0d>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue (Newtonsoft.Json.Serialization.JsonProperty property, Newtonsoft.Json.JsonConverter propertyConverter, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerProperty, Newtonsoft.Json.JsonReader reader, System.Object target) (at <f74995119334484fb6db6825be2eac0d>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject (System.Object newObject, Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Serialization.JsonObjectContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.String id) (at <f74995119334484fb6db6825be2eac0d>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <f74995119334484fb6db6825be2eac0d>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) (at <f74995119334484fb6db6825be2eac0d>:0)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) (at <f74995119334484fb6db6825be2eac0d>:0)
Newtonsoft.Json.JsonSerializer.DeserializeInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType) (at <f74995119334484fb6db6825be2eac0d>:0)
Newtonsoft.Json.JsonSerializer.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType) (at <f74995119334484fb6db6825be2eac0d>:0)
Newtonsoft.Json.JsonSerializer.Deserialize[T] (Newtonsoft.Json.JsonReader reader) (at <f74995119334484fb6db6825be2eac0d>:0)
Algorand.V2.Algod.DefaultApi+<ReadObjectResponseAsync>d__49`1[T].MoveNext () (at <e37046d708ca4190ac0adbd36820b4e6>:0)
Rethrow as ApiException: Could not deserialize the response body stream as Algorand.V2.Algod.Model.Account.
Status: 200
Response:
Algorand.V2.Algod.DefaultApi+<ReadObjectResponseAsync>d__49`1[T].MoveNext () (at <e37046d708ca4190ac0adbd36820b4e6>:0)

**Comment by FrankSzendzielarz** [comment]
Fixed for now. Thanks for the heads up @JoshOtter
